export const countryToCode: { [key: string]: string } = {
  "India": "IN",
  "United States": "US",
  "United States of America": "US",
  "Russia": "RU",
  "Russian Federation": "RU",
  "Germany": "DE",
  "France": "FR",
  "Canada": "CA",
  "Australia": "AU",
  "Spain": "ES",
  "Italy": "IT",
  "Netherlands": "NL",
  "Brazil": "BR",
  "China": "CN",
  "Japan": "JP",
  "South Korea": "KR",
  "Singapore": "SG",
  "Seychelles": "SC",
  "United Arab Emirates": "AE",
  "United Kingdom": "GB",
  "UK": "GB",
  "Sweden": "SE",
  "Norway": "NO",
  "Denmark": "DK",
  "Finland": "FI",
  "Switzerland": "CH",
  "Austria": "AT",
  "Belgium": "BE",
  "Ireland": "IE",
  "Poland": "PL",
  "Portugal": "PT",
  "Mexico": "MX",
  "Argentina": "AR",
  "Chile": "CL",
  "Colombia": "CO",
  "Peru": "PE",
  "Turkey": "TR",
  "Saudi Arabia": "SA",
  "Indonesia": "ID",
  "Thailand": "TH",
  "Malaysia": "MY",
  "Vietnam": "VN",
  "Philippines": "PH",
  "South Africa": "ZA",
  "Nigeria": "NG",
  "Kenya": "KE",
  "Egypt": "EG",
  "Israel": "IL",
  "New Zealand": "NZ",
  "Czech Republic": "CZ",
  "Romania": "RO",
  "Hungary": "HU",
  "Ukraine": "UA",
  "Pakistan": "PK",
  "Bangladesh": "BD",
  "Sri Lanka": "LK",
  "Nepal": "NP",
  "Morocco": "MA",
  "Greece": "GR",
  "Luxembourg": "LU",
  "Slovakia": "SK",
  "Slovenia": "SI",
  "Croatia": "HR",
  "Estonia": "EE",
  "Latvia": "LV",
  "Lithuania": "LT",
  "Iceland": "IS",
  "Qatar": "QA",
  "Kuwait": "KW",
  "Oman": "OM",
  "Jordan": "JO",
  "Kazakhstan": "KZ",
  "Serbia": "RS",
  "Georgia": "GE",
  "Armenia": "AM",
  "Uzbekistan": "UZ",
  "Belarus": "BY",
  "Bulgaria": "BG",
  "Bosnia and Herzegovina": "BA",
  "Malta": "MT",
  "Cyprus": "CY",
  "Tunisia": "TN",
  "Algeria": "DZ",
  "Iraq": "IQ",
  "Iran": "IR",
  "Afghanistan": "AF",
  "Myanmar": "MM",
  "Cambodia": "KH",
  "Laos": "LA",
  "Mongolia": "MN",
  "Taiwan": "TW",
  "Hong Kong": "HK",
  "Macau": "MO",
  "Palestine": "PS",
  "Unknown": "UN"
};


export const getFlagURL = (countryName: string) => {
  const code = countryToCode[countryName] || "XX";
  return `https://flagcdn.com/${code.toLowerCase()}.svg`;
};
